name: publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: install dependencies
      run: |
        pip install build twine
    - uses: actions/checkout@v3
    - name: build distribution
      run: |
        python -m build
        twine upload --repository-url https://github.com/brandon-sexton/pyxis/packages dist/*
