name: documentation

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - uses: actions/checkout@v3
    - name: build html
      uses: ammaraskar/sphinx-action@master
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.PYXIS_CI_TOKEN }}
        publish_dir: docs/build/html
