name: documentation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: install dependencies
      run: |
        pip install sphinx
    - uses: actions/checkout@v3
    - name: build html
      run: |
        git checkout -b gh-pages
        cd ./docs
        make html
        cd ../
    - name: deploy
      run: |
        git add *
        git commit -m "documentation update"
        git push origin HEAD
